# Audio LED Visualization System Configuration

audio:
  sample_rate: 44100
  channels: 2
  chunk_size: 2048
  play_audio: true
  resample: true  # Enable automatic resampling for files with unsupported sample rates
  use_jack: false

processing:
  fft_enabled: true
  window_type: blackman
  bands: 64
  smoothing: 0.5

visual:
  output_method: display  # Use 'display' for visualization, 'file' for text output
  output_file: "./rgb_output.txt"  # Used when output_method is 'file'
  color_mode: colorful
  brightness: 255
  refresh_rate: 30

system:
  log_level: info
  dependencies_check: true
